
/**
 * @file rootkeypackage_json_properties.h
 * @brief The root key package json property name and value definitions.
 *
 * @copyright Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 */

#define ADUC_ROOTKEY_PACKAGE_PROPERTY_PROTECTED "protected"
#define ADUC_ROOTKEY_PACKAGE_PROPERTY_ISTEST "isTest"
#define ADUC_ROOTKEY_PACKAGE_PROPERTY_VERSION "version"
#define ADUC_ROOTKEY_PACKAGE_PROPERTY_PUBLISHED "published"
#define ADUC_ROOTKEY_PACKAGE_PROPERTY_DISABLED_ROOT_KEYS "disabledRootKeys"
#define ADUC_ROOTKEY_PACKAGE_PROPERTY_DISABLED_SIGNING_KEYS "disabledSigningKeys"
#define ADUC_ROOTKEY_PACKAGE_PROPERTY_HASH "hash"
#define ADUC_ROOTKEY_PACKAGE_PROPERTY_KEY_TYPE "keyType"
#define ADUC_ROOTKEY_PACKAGE_PROPERTY_KEY_TYPE_RSA "RSA"
#define ADUC_ROOTKEY_PACKAGE_PROPERTY_RSA_MODULUS "n"
#define ADUC_ROOTKEY_PACKAGE_PROPERTY_RSA_EXPONENT "e"
#define ADUC_ROOTKEY_PACKAGE_PROPERTY_ROOTKEYS "rootKeys"
#define ADUC_ROOTKEY_PACKAGE_PROPERTY_SIGNATURES "signatures"
#define ADUC_ROOTKEY_PACKAGE_PROPERTY_ALG "alg"
#define ADUC_ROOTKEY_PACKAGE_PROPERTY_SIG "sig"
#define ADUC_ROOTKEY_PACKAGE_PROPERTY_SIGNATURE_ALG_RS256 "RS256"
#define ADUC_ROOTKEY_PACKAGE_PROPERTY_SIGNATURE_ALG_RS384 "RS384"
#define ADUC_ROOTKEY_PACKAGE_PROPERTY_SIGNATURE_ALG_RS512 "RS512"
