if (NOT WIN32)
    if (ADUC_BUILD_DELTA_HANDLER)
        message (STATUS "Building Microsoft Delta Download Handler")
        add_subdirectory (microsoft_delta_download_handler)
    else ()
        message (STATUS "Skipping Microsoft Delta Download Handler (ADUC_BUILD_DELTA_HANDLER is OFF)")
    endif ()
endif ()
