variables:
  version.major: 0
  version.minor: 8
  version.patch: 0
  version.pre-release: "public-preview"
  version.build: $[format('{0:yyyyMMdd}-{0:HHmmss}', pipeline.startTime)]

  # Environment variables for all client builds:
  ADUC_VERSION_MAJOR: $(version.major)
  ADUC_VERSION_MINOR: $(version.minor)
  ADUC_VERSION_PATCH: $(version.patch)
  ADUC_VERSION_PRERELEASE: $(version.pre-release)
  ADUC_VERSION_BUILD: $(version.build)
  ADUC_DEBIAN_PACKAGE_ARCHITECTURE: "amd64"

  ENABLE_ADU_TELEMETRY_REPORTING: true
  # ADUC_BUILDER_IDENTIFIER will be set to "DU" short for Device Update by default, for Device Update-sourced builder
  ADUC_BUILDER_IDENTIFIER: DU
  # DO requires gcc greater than 6 for c++17 support.
  # gcc-8 matches what is built with poky warrior.
  CC: gcc-8
  CXX: g++-8

name: $(version.major).$(version.minor).$(version.patch)-$(version.pre-release)+$(version.build)

resources:
  - repo: self

trigger:
  branches:
    include:
      - main
      - release/*
      - feature/*
      - dev/*
  paths:
    exclude:
      - docs/*
      - README.md
      - LICENSE.md
      - .clang-format
      - .cmake-format.json
      - tools/*
      - docker/*
      - scripts/*

pr:
  branches:
    include:
      - main
      - release/*
      - feature/*
      - dev/*
  paths:
    exclude:
      - docs/*
      - README.md
      - LICENSE.md
      - .clang-format
      - .cmake-format.json
      - docker/*
      - licenses/*

jobs:
  - job: BuildAduAgent
    displayName: "Build ADU Agent"
    timeoutInMinutes: 60
    cancelTimeoutInMinutes: 60
    pool: aduc_1es_client_pool
    steps:
      - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
        displayName: "Component Detection"
        inputs:
          sourceScanPath: src

      - task: Bash@3
        displayName: "Install ADUC dependencies"
        inputs:
          targetType: "filePath"
          filePath: $(Build.SourcesDirectory)/scripts/install-deps.sh
          arguments: --install-aduc-deps --install-packages --install-do-deps-distro ubuntu1804

      - task: Bash@3
        displayName: "Build Client, Unit Tests and Packages: linux-MinSizeRel"
        inputs:
          targetType: "filePath"
          filePath: $(Build.SourcesDirectory)/scripts/build.sh
          arguments: "--clean --type MinSizeRel --platform-layer linux --log-lib zlog --build-packages --build-unit-tests --static-analysis clang-tidy,cppcheck --out-dir $(Build.BinariesDirectory)"

      - bash: |
          cp $(Build.BinariesDirectory)/*.deb $(Build.ArtifactStagingDirectory)
          cp $(Build.BinariesDirectory)/bin/AducIotAgent $(Build.ArtifactStagingDirectory)/AducIotAgent
        displayName: "Stage build artifacts (Deb package, agent and docs)"
        condition: and(ne(variables['Build.Reason'], 'IndividualCI'), ne(variables['Build.Reason'], 'PullRequest'))

        # Run all unit tests.
      - bash: |
          ctest -T test -V --output-on-failure
          exit $?
        displayName: "Run Unit Tests: linux-MinSizeRel"
        workingDirectory: $(Build.BinariesDirectory)

      - task: PublishTestResults@2
        displayName: "Publish Unit Test Results: linux-MinSizeRel"
        condition: succeededOrFailed() # Run this task even if tests fail.
        inputs:
          testResultsFormat: cTest
          testResultsFiles: "Testing/**/*.xml"
          searchFolder: $(Build.BinariesDirectory)
          failTaskOnFailedTests: true
          publishRunAttachments: false # Attachments are not supported for CTest

      - task: Bash@3
        displayName: "Build Client and Unit Tests: linux-Debug"
        inputs:
          targetType: "filePath"
          filePath: $(Build.SourcesDirectory)/scripts/build.sh
          arguments: "--clean --build-unit-tests --platform-layer linux --log-lib zlog --static-analysis clang-tidy,cppcheck --out-dir $(Build.BinariesDirectory)"

        # Run all unit tests.
      - bash: |
          ctest -T test -V --output-on-failure
          exit $?
        displayName: "Run Unit Tests: linux-Debug"
        workingDirectory: $(Build.BinariesDirectory)

      - task: PublishTestResults@2
        displayName: "Publish Unit Test Results: linux-Debug"
        condition: succeededOrFailed() # Run this task even if tests fail.
        inputs:
          testResultsFormat: cTest
          testResultsFiles: "Testing/**/*.xml"
          searchFolder: $(Build.BinariesDirectory)
          failTaskOnFailedTests: true
          publishRunAttachments: false # Attachments are not supported for CTest

      - task: PublishPipelineArtifact@0
        displayName: "Publish Pipeline Artifacts"
        condition: and(succeeded(), ne(variables['Build.Reason'], 'IndividualCI'), ne(variables['Build.Reason'], 'PullRequest'))
        inputs:
          artifactName: "adu-linux-client"
          targetPath: "$(Build.ArtifactStagingDirectory)"

        # Ignore SC2164: Use 'cd ... || exit' or 'cd ... || return' in case cd fails.
        #   We usually want to return an error code from a specific, previous command
        #   even if popd, pushd, or cd fails.
        # Ignore SC2209: Use var=$(command) to assign output (or quote to assign string).
        #   We use 'ret=return' or 'ret=exit' to support dot sourcing.
      - bash: |
          sudo apt install -y shellcheck
          shellcheck -s bash -e SC2164 -e SC2209 $(find -name "*.sh")
          exit $?
        displayName: "Run ShellCheck"

      - task: ComponentGovernanceComponentDetection@0
        inputs:
          scanType: "Register"
          verbosity: "Verbose"
          alertWarningLevel: "High"
