name: deviceupdate-agent # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: IoT Hub Device Update Agent for Ubuntu Core # 79 char long summary
description: |
   A proof-of-concept for the Device Update Agent Ubuntu Core snap.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

#####
#
# Keywords
#
# after  - Specifies part's dependencies.
#              See https://snapcraft.io/docs/parts-lifecycle#heading--step-dependencies
#                  https://snapcraft.io/docs/parts-lifecycle
# plugin - Specifies a plugin required for building the part.
#
# see also:
#     environment variables - https://snapcraft.io/docs/parts-environment-variables
#
#####

parts:
  installdeps:
    plugin: nil
    source: .
    override-build: |
      ./scripts/install-deps.sh -a
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib
      cp /usr/local/lib/libdeliveryoptimization.so* $SNAPCRAFT_PART_INSTALL/usr/lib
    stage-packages:
      - libboost-filesystem1.71.0
  #
  # Agent component
  # This is the main agent application.
  #
  agent:
    plugin: nil
    source: .
    override-build: |
      ./scripts/build.sh --ubuntu-core-snap-only
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/adu
      mkdir -p $SNAPCRAFT_PART_INSTALL/var/lib/adu/extensions/sources
      mkdir -p $SNAPCRAFT_PART_INSTALL/conf
      cp $SNAPCRAFT_PART_BUILD/out/bin/AducIotAgent $SNAPCRAFT_PART_INSTALL/usr/bin/AducIotAgent
      cp $SNAPCRAFT_PART_BUILD/out/bin/adu-shell $SNAPCRAFT_PART_INSTALL/usr/lib/adu
      cp $SNAPCRAFT_PART_BUILD/out/lib/*.so $SNAPCRAFT_PART_INSTALL/var/lib/adu/extensions/sources

    # Require install-deps
    after:
     - installdeps
    stage:
      - usr/bin/*
      - usr/lib/*
      - usr/lib/adu/*
      - var/lib/adu/extensions/sources/*.so
      - conf/*.*
    stage-packages:
      - libasn1-8-heimdal
      - libboost-filesystem1.71.0
      - libbrotli1
      - libcurl4
      - libgssapi3-heimdal
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libicu66
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libnghttp2-14
      - libpsl5
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libssh-4
      - libwind0-heimdal
      - libxml2

apps:
  # high-privilege tasks broker
  adu-shell:
    command: usr/lib/adu/adu-shell
    plugs:
      - home
      - network

  # 'deviceupdate-agent' service
  # See document: https://forum.snapcraft.io/t/snapcraft-app-and-service-metadata/8335
  deviceupdate-agent:
    command: usr/bin/AducIotAgent
    daemon: simple
    refresh-mode: restart
    restart-condition: always
    restart-delay: 10s
    plugs:
      - network

environment:
  LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"

layout:
# adu_data_dir
  /var/lib/adu:
    symlink: $SNAP_DATA/data
# adu_conf_dir
  /etc/adu:
    symlink: $SNAP_DATA/config
# adu_shell_dir
  /usr/lib/adu:
    symlink: $SNAP/usr/lib/adu
# adu_log_dir
  /var/log/adu:
    symlink: $SNAP_DATA/log
