#!/bin/sh

# adu_user is the user that the ADU Agent daemon will run as.
# ADU Agent daemon needs to run as 'adu' to be able to perform high-privilege tasks via adu-shell.
adu_user=snap_aziot_du

# The adu_group is the group that gives partner users like DO user
# access to ADU resources like download sandbox folder.
adu_group=snap_aziot_du

#
# exit codes
#
exitcode_success=0
exitcode_adu_group_already_exists=1
exitcode_adu_user_already_exists=2
exitcode_pre_ppr_installed=3 # pre-ppr agent binary is installed
exitcode_pre_ppr_unpurged=4  # pre-ppr config exists
exitcode_unknown_argument=5

add_adu_user_and_group() {
    echo "Create the 'adu' group."
    if ! getent group "$adu_group" > /dev/null; then
        addgroup --system "$adu_group"
    else
        # For security purposes, it's extremely important that there's no existing 'adu' user and 'adu' group.
        # This ensures the account and group are setup by our package installation process only,
        # and no other actor can pre-create the user/group with nefarious intentions.
        echo "Error: 'adu' group already exists." >&2
        exit $exitcode_adu_group_already_exists
    fi

    echo "Create the 'adu' user." # With no shell and no login, in 'adu' group.
    if ! getent passwd "$adu_user" > /dev/null; then
        adduser --system "$adu_user" --ingroup "$adu_group" --no-create-home --shell /bin/false
    else
        # For security purposes, it's extremely important that there's no existing 'adu' user and 'adu' group.
        # This to ensures the account and group are setup by our package installation process only,
        # and no other actor can pre-create the user/group with nefarious intentions.
        echo "Error: 'adu' user already exists." >&2
        exit $exitcode_adu_user_already_exists
    fi

    echo "Add the 'adu' user to the 'syslog' group." # To allow ADU to write to /var/log folder
    if getent group "syslog" > /dev/null; then
        usermod -aG "syslog" "$adu_user"
    fi
}

add_adu_user_and_group
